apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab
  labels:
    app: main
    service: ab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
      service: ab
  template:
    metadata:
      labels:
        app: main
        service: ab
    spec:
      containers:
      - name: ab-container
        image: hhana982/serviceb:1.<version>
        ports:
        - containerPort: 5000
        env: 
        - name: num
          value: "5"