apiVersion: v1
kind: Service
metadata:
  name: ab
  labels:
    app: serviceB
    service: ab
spec:
  selector:
    app: serviceB
    service: ab
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP